### ISSUE TITLE
Review Controller: PATCH Update and POST Create test fail

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#1]
This test fails because reviews_url is not a proper url in the Review controller

Failure/Error: post :create, user_id:@user.id, review:@review
     NoMethodError:
       undefined method `review_url' for #ReviewsController:0x007fef17c682d0

review_controller.rb:
def create
....
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
....
end

def update
....
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
....
end

**Comment by anthonytokosky** [comment]
Yo shachi. thanks for opening this up!

Have you run `$ rake routes` in the terminal and verified that the `review_url` exists? I'm thinking that the path looks something like `/users/:user_id/reviews/review_id`, so you would need to include the `:user_id` in the helper path. It would look something like this (using `user_id: 35` as an example):

`format.html { redirect_to @review(35), notice: 'Review was successfully updated.' }`

**Comment by shachiagarwalla** [comment]
user_reviews is the url i guess you are talking about. 
/users/:user_id/reviews/:id(.:format)

**Comment by anthonytokosky** [comment]
yeah thats the one. So the idea is that you need to include the user id in the path, or else the controller won't know which user the path is trying to reference. Example: 

`user_reviews_path` - this doesn't make sense, because which user are you talking about?
`user_reviews_path(2)` - this means "give me all the reviews for user with `id: 2`" 

Let me know if this makes sense.

**Comment by shachiagarwalla** [comment]
Works well now
