### ISSUE TITLE
Current user himself shown as Tutor search result

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#4]
I searched for a tutor in a skill I specialized and it showed my name as the result:

Search Result:
First name: shachi
First name: shachi
First name: shachi

Should we allow this kind of behavior?

**Comment by anthonytokosky** [comment]
This is undesired behavior.
Resolved in commit: d517faf69f25d8b0f7ea5ac079f6572c7710c651

@shachiagarwalla please update your branch with this fix, and test. In order to easily update your branch, just do this: 

`git checkout master`
`git pull origin master`
`git checkout testing`
`git rebase master`

This will get the newest master branch, and then stack all your new commits on testing on top of those changes. 

If tests pass, go ahead and close the issue. Thanks

**Comment by shachiagarwalla** [comment]
Resolved
